# Generated by Django 4.2.28 on 2026-02-08 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0003_subscription_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_crypto', models.BooleanField(default=False)),
                ('crypto_symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('crypto_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('is_credit_card', models.BooleanField(default=False)),
                ('cutoff_date', models.IntegerField(blank=True, null=True)),
                ('payment_date', models.IntegerField(blank=True, null=True)),
                ('issuer_bank', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_entities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GamificationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_freezes', models.IntegerField(default=3)),
                ('repaired_days', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
