# Generated by Django 4.2.28 on 2026-02-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_visionentity_gamificationstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='visionentity',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual interest rate (percentage)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='visionentity',
            name='minimum_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
