# Generated by Django manually

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_visionentity_interest_rate_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS wallet_subscription CASCADE;",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurrence_frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='last_recurrence_date',
            field=models.DateTimeField(blank=True, help_text='Last time a recurring transaction was generated from this one', null=True),
        ),
    ]
