// Smart Categorization Keywords Mapping
export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  "🍻 Bares": [
    "bar",
    "cerveza",
    "alcohol",
    "antro",
    "pub",
    "drinks",
    "vino",
    "licor",
  ],
  "🍽️ Restaurantes": [
    "restaurante",
    "comida",
    "cena",
    "almuerzo",
    "desayuno",
    "vips",
    "toks",
    "sanborns",
    "sushi",
    "pizza",
    "tacos",
    "wings",
    "italiannis",
  ],
  "🍔 Delivery": [
    "uber eats",
    "rappi",
    "didi food",
    "delivery",
    "domicilio",
    "pedidos ya",
  ],
  "🍽️ Alimentos": ["abarrotes", "tienda", "market"],
  "🏠 Casa": [
    "renta",
    "alquiler",
    "mantenimiento",
    "reparacion",
    "mueble",
    "ikea",
    "home depot",
    "sodimac",
  ],
  "🚗 Transporte": [
    "uber",
    "didi",
    "cabify",
    "taxi",
    "bus",
    "metro",
    "gasolina",
    "pemex",
    "shell",
    "bp",
    "estacionamiento",
    "peaje",
    "caseta",
  ],
  "💰 Salario": ["nomina", "sueldo", "pago", "deposito", "honorarios"],
  "🎁 Regalo": ["regalo", "cumpleaños", "navidad", "boda", "fiesta"],
  "🛒 Supermercado": [
    "walmart",
    "costco",
    "soriana",
    "chedraui",
    "oxxo",
    "7eleven",
    "super",
    "despensa",
    "heb",
    "city market",
    "fresko",
    "la comer",
  ],
  "💊 Salud": [
    "farmacia",
    "doctor",
    "medico",
    "hospital",
    "dentista",
    "consulta",
    "medicina",
    "similares",
    "san pablo",
    "guadalajara",
  ],
  "🎮 Entretenimiento": [
    "netflix",
    "spotify",
    "cine",
    "cinepolis",
    "cinemex",
    "steam",
    "playstation",
    "xbox",
    "juego",
    "hbo",
    "disney",
    "prime",
    "icloud",
    "apple music",
    "youtube",
  ],
  "🎓 Educación": [
    "curso",
    "escuela",
    "universidad",
    "colegiatura",
    "libro",
    "udemy",
    "platzi",
    "coursera",
  ],
  "✈️ Viajes": [
    "vuelo",
    "avion",
    "hotel",
    "airbnb",
    "viaje",
    "vacaciones",
    "aeromexico",
    "volaris",
    "vivaaerobus",
    "booking",
  ],
  "🧾 Servicios": [
    "cfe",
    "luz",
    "agua",
    "gas",
    "internet",
    "telcel",
    "at&t",
    "movistar",
    "telefono",
    "plan",
    "totalplay",
    "izzi",
    "megacable",
    "sky",
  ],
};

/**
 * Predicts a category based on the description string.
 * Returns the matching category name or null if no match is found.
 */
export const predictCategory = (description: string): string | null => {
  if (!description) return null;

  const lowerDesc = description.toLowerCase();
  for (const [category, keywords] of Object.entries(CATEGORY_KEYWORDS)) {
    if (keywords.some((keyword) => lowerDesc.includes(keyword))) {
      return category;
    }
  }
  return null;
};
